### ISSUE TITLE
Dropulation

### ISSUE THREAD

**Issue by emattei** [broadinstitute/epi-SHARE-seq-pipeline#98]

**Comment by sidwekhande** [comment]
Subwf and task defined here: [Dockstore link](https://dockstore.org/workflows/github.com/broadinstitute/broad-epi-workflows-collection/DropulationAssignDonors:main?tab=info)

Subwf can take rna, atac, or both BAMs as inputs, run Dropulation with the correct parameters, and write the barcode-donor assignments in txt.gz and vcf.gz output files.
